#include "headers.h"

#include "dispobject.cpp"
#include "entity.cpp"
#include "bot.cpp"
#include "player.cpp"
#include "pathfindcell.cpp"
#include "map.cpp"
#include "soundcontrol.cpp"
#include "controls.cpp"
#include "dispcontrol.cpp"
#include "game.cpp"